markw: remove generic(?) Health HAL modules
Actually this commit should be neeeded because of the last healthd-related changes I've made since this one https://github.com/NotesOfReality/android_device_xiaomi_markw/commit/79c0db2bbb5138fd8120bec2370dc48f6470c23f .
This commit MAY also be needed https://gitlab.com/sayan7848/android_system_core/commit/de7d92b1e9ec3ac59e5d17e860351f17f3d166b9 , at anyway it won't hurt anybody so cherry-pick it.

This commit is a fix for the following building process error :

[ 18% 827/4470] Import includes file: /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/STATIC_LIBRARIES/libhealthd.msm_intermediates/import_includes
[ 18% 828/4470] Import includes file: /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/SHARED_LIBRARIES/android.hardware.health@1.0-impl_intermediates/import_includes
[ 18% 829/4470] target thumb C++: android.hardware.health@1.0-impl_32 <= hardware/interfaces/health/1.0/default/Health.cpp
[ 18% 830/4470] target SharedLib: libloc_stub_32 (/home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/SHARED_LIBRARIES/libloc_stub_intermediates/LINKED/libloc_stub.so)
[ 18% 831/4470] target Pack Relocations: libloc_stub_32 (/home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/SHARED_LIBRARIES/libloc_stub_intermediates/PACKED/libloc_stub.so)
[ 18% 832/4470] target Symbolic: libloc_stub_32 (/home/droidmother/DU-O_CAF/out/target/product/markw/symbols/vendor/lib/libloc_stub.so)
[ 18% 833/4470] target thumb C++: libhealthd.msm_32 <= device/xiaomi/markw/healthd/healthd_msm_alarm.cpp
[ 18% 834/4470] target thumb C++: libhealthd.msm_32 <= device/xiaomi/markw/healthd/healthd_board_msm.cpp
[ 18% 835/4470] Install: /home/droidmother/DU-O_CAF/out/target/product/markw/vendor/lib/hw/android.hardware.keymaster@3.0-impl.so
[ 18% 836/4470] Install: /home/droidmother/DU-O_CAF/out/target/product/markw/vendor/lib/hw/android.hardware.memtrack@1.0-impl.so
[ 18% 837/4470] Install: /home/droidmother/DU-O_CAF/out/target/product/markw/vendor/lib/hw/android.hardware.renderscript@1.0-impl.so
[ 18% 838/4470] Install: /home/droidmother/DU-O_CAF/out/target/product/markw/vendor/lib/hw/android.hardware.sensors@1.0-impl.so
[ 18% 839/4470] Install: /home/droidmother/DU-O_CAF/out/target/product/markw/vendor/lib/hw/android.hardware.soundtrigger@2.0-impl.so
[ 18% 840/4470] Install: /home/droidmother/DU-O_CAF/out/target/product/markw/vendor/lib/hw/android.hardware.thermal@1.0-impl.so
[ 18% 841/4470] Install: /home/droidmother/DU-O_CAF/out/target/product/markw/vendor/lib/hw/android.hardware.vibrator@1.0-impl.so
[ 18% 842/4470] Check module type: /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/STATIC_LIBRARIES/libhealthd.msm_intermediates/link_type
[ 18% 843/4470] Install: /home/droidmother/DU-O_CAF/out/target/product/markw/vendor/lib/hw/audio.primary.default.so
[ 18% 844/4470] Check module type: /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/SHARED_LIBRARIES/android.hardware.health@1.0-impl_intermediates/link_type
[ 18% 845/4470] target StaticLib: libhealthd.msm_32 (/home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/STATIC_LIBRARIES/libhealthd.msm_intermediates/libhealthd.msm.a)
[ 18% 846/4470] target SharedLib: android.hardware.health@1.0-impl_32 (/home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/SHARED_LIBRARIES/android.hardware.health@1.0-impl_intermediates/LINKED/android.hardware.health@1.0-impl.so)
FAILED: /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/SHARED_LIBRARIES/android.hardware.health@1.0-impl_intermediates/LINKED/android.hardware.health@1.0-impl.so 
/bin/bash -c "/usr/bin/ccache prebuilts/clang/host/linux-x86/clang-4053586/bin/clang++ -nostdlib -Wl,-soname,android.hardware.health@1.0-impl.so -Wl,--gc-sections -shared /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/crtbegin_so.o /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/SHARED_LIBRARIES/android.hardware.health@1.0-impl_intermediates/Health.o -Wl,--whole-archive  -Wl,--no-whole-archive   /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/STATIC_LIBRARIES/android.hardware.health@1.0-convert_intermediates/android.hardware.health@1.0-convert.a  /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/STATIC_LIBRARIES/libunwind_llvm_intermediates/libunwind_llvm.a  /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/STATIC_LIBRARIES/libhealthd.msm_intermediates/libhealthd.msm.a  /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/STATIC_LIBRARIES/libcompiler_rt-extras_intermediates/libcompiler_rt-extras.a   /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/STATIC_LIBRARIES/libatomic_intermediates/libatomic.a /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/STATIC_LIBRARIES/libgcc_intermediates/libgcc.a -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--build-id=md5 -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--icf=safe -Wl,--hash-style=gnu -Wl,--no-undefined-version -Wl,--no-fix-cortex-a8   -target arm-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin -Wl,--exclude-libs,libunwind_llvm.a -Wl,--no-undefined /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/libcutils.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/libhidlbase.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/libhidltransport.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/liblog.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/libutils.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/libbase.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/libpng.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/android.hardware.health@1.0.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/libc++.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/libc.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/libm.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/libdl.so -o /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/SHARED_LIBRARIES/android.hardware.health@1.0-impl_intermediates/LINKED/android.hardware.health@1.0-impl.so /home/droidmother/DU-O_CAF/out/target/product/markw/obj_arm/lib/crtend_so.o"
device/xiaomi/markw/healthd/healthd_board_msm.cpp:209: error: undefined reference to 'gr_font_size(GRFont const*, int*, int*)'
device/xiaomi/markw/healthd/healthd_board_msm.cpp:211: error: undefined reference to 'gr_measure(GRFont const*, char const*)'
device/xiaomi/markw/healthd/healthd_board_msm.cpp:212: error: undefined reference to 'gr_fb_width()'
device/xiaomi/markw/healthd/healthd_board_msm.cpp:213: error: undefined reference to 'gr_fb_height()'
device/xiaomi/markw/healthd/healthd_board_msm.cpp:214: error: undefined reference to 'gr_color(unsigned char, unsigned char, unsigned char, unsigned char)'
device/xiaomi/markw/healthd/healthd_board_msm.cpp:215: error: undefined reference to 'gr_text(GRFont const*, int, int, char const*, bool)'
device/xiaomi/markw/healthd/healthd_board_msm.cpp:314: error: undefined reference to 'gr_init_font(char const*, GRFont**)'
device/xiaomi/markw/healthd/healthd_board_msm.cpp:319: error: undefined reference to 'gr_sys_font()'
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)